## Sample configuration for elo-web-service
#
# You can override these with environment variables, e.g.
# ELO_WEB_SERVICE_GOOGLE_SERVICE_ACCOUNT_KEY=/path/to/key.json

# Path to the Google service account file. 
# The file is sensitive and should not be commited.
google_service_account_key: "../google-service-account-key.json"

# Google sheet document identifier to read and store data (value afte /d/ in url)
# https://docs.google.com/spreadsheets/d/1tOWQdwLUTAJyVlQwnWEMTjL0h-Wk08wB443PUWBtztY/
doc_id: "1tOWQdwLUTAJyVlQwnWEMTjL0h-Wk08wB443PUWBtztY"

# Interface and port to listen to
address: "localhost:8080"

# Oauth2 initial url
oauth2_auth_uri: https://accounts.google.com/o/oauth2/auth

# Oauth2 callback url
oauth2_redirect_uri: http://localhost:3000/oauth2-callback

# Oauth2 url to get ID and access token
oauth2_token_uri: https://oauth2.googleapis.com/token

# Frontend domain and scheme
frontend_uri: http://localhost:3000

# Cookie expiration time in seconds
cookie_ttl_seconds: 86400
